import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=7b05qwh4yi"></Script>
        {children}
      </body>
    </html>
  );
}
